name: "CI 🧪"

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Generate and Publish Allure Report
        uses: simple-setup/allure-report-action@v1
        with:
          results-dir: build/allure-results
          report-dir: build/allure-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
